name: CI-MARCOS-EDUARDO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Configurando ambiente JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Excutando os testes e construindo o projeto
        run: mvn test
        
      - name: Comentando PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Obrigado pela PR. Ela será será revisada em breve !'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
